allowBuilds:
  '@parcel/watcher': true
  '@tsparticles/engine': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@tsparticles/basic@4.1.1'
  - '@tsparticles/canvas-utils@4.1.1'
  - '@tsparticles/engine@4.1.1'
  - '@tsparticles/interaction-external-attract@4.1.1'
  - '@tsparticles/interaction-external-bounce@4.1.1'
  - '@tsparticles/interaction-external-bubble@4.1.1'
  - '@tsparticles/interaction-external-connect@4.1.1'
  - '@tsparticles/interaction-external-destroy@4.1.1'
  - '@tsparticles/interaction-external-drag@4.1.1'
  - '@tsparticles/interaction-external-grab@4.1.1'
  - '@tsparticles/interaction-external-parallax@4.1.1'
  - '@tsparticles/interaction-external-pause@4.1.1'
  - '@tsparticles/interaction-external-push@4.1.1'
  - '@tsparticles/interaction-external-remove@4.1.1'
  - '@tsparticles/interaction-external-repulse@4.1.1'
  - '@tsparticles/interaction-external-slow@4.1.1'
  - '@tsparticles/interaction-external-trail@4.1.1'
  - '@tsparticles/interaction-particles-attract@4.1.1'
  - '@tsparticles/interaction-particles-collisions@4.1.1'
  - '@tsparticles/interaction-particles-links@4.1.1'
  - '@tsparticles/plugin-absorbers@4.1.1'
  - '@tsparticles/plugin-blend@4.1.1'
  - '@tsparticles/plugin-easing-quad@4.1.1'
  - '@tsparticles/plugin-emitters-shape-circle@4.1.1'
  - '@tsparticles/plugin-emitters-shape-square@4.1.1'
  - '@tsparticles/plugin-emitters@4.1.1'
  - '@tsparticles/plugin-hex-color@4.1.1'
  - '@tsparticles/plugin-hsl-color@4.1.1'
  - '@tsparticles/plugin-interactivity@4.1.1'
  - '@tsparticles/plugin-move@4.1.1'
  - '@tsparticles/plugin-rgb-color@4.1.1'
  - '@tsparticles/react@4.1.1'
  - '@tsparticles/shape-circle@4.1.1'
  - '@tsparticles/shape-emoji@4.1.1'
  - '@tsparticles/shape-image@4.1.1'
  - '@tsparticles/shape-line@4.1.1'
  - '@tsparticles/shape-polygon@4.1.1'
  - '@tsparticles/shape-square@4.1.1'
  - '@tsparticles/shape-star@4.1.1'
  - '@tsparticles/shape-text@4.1.1'
  - '@tsparticles/slim@4.1.1'
  - '@tsparticles/updater-destroy@4.1.1'
  - '@tsparticles/updater-life@4.1.1'
  - '@tsparticles/updater-opacity@4.1.1'
  - '@tsparticles/updater-out-modes@4.1.1'
  - '@tsparticles/updater-paint@4.1.1'
  - '@tsparticles/updater-roll@4.1.1'
  - '@tsparticles/updater-rotate@4.1.1'
  - '@tsparticles/updater-size@4.1.1'
  - '@tsparticles/updater-tilt@4.1.1'
  - '@tsparticles/updater-twinkle@4.1.1'
  - '@tsparticles/updater-wobble@4.1.1'
  - tsparticles@4.1.1
